// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: bridge.proto

package gwconn

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Bridge_Login_FullMethodName           = "/gwconn.Bridge/Login"
	Bridge_Register_FullMethodName        = "/gwconn.Bridge/Register"
	Bridge_GetTargetStream_FullMethodName = "/gwconn.Bridge/GetTargetStream"
	Bridge_CallDnsAcme_FullMethodName     = "/gwconn.Bridge/CallDnsAcme"
	Bridge_SendSystemStat_FullMethodName  = "/gwconn.Bridge/SendSystemStat"
	Bridge_SendRouteInfo_FullMethodName   = "/gwconn.Bridge/SendRouteInfo"
	Bridge_SendLog_FullMethodName         = "/gwconn.Bridge/SendLog"
)

// BridgeClient is the client API for Bridge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BridgeClient interface {
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
	Register(ctx context.Context, in *BridgeInfo, opts ...grpc.CallOption) (*RegisterResp, error)
	GetTargetStream(ctx context.Context, in *JoinStreamReq, opts ...grpc.CallOption) (Bridge_GetTargetStreamClient, error)
	CallDnsAcme(ctx context.Context, in *DnsAcmeReq, opts ...grpc.CallOption) (*empty.Empty, error)
	SendSystemStat(ctx context.Context, in *SystemStat, opts ...grpc.CallOption) (*empty.Empty, error)
	SendRouteInfo(ctx context.Context, in *RouteStat, opts ...grpc.CallOption) (*empty.Empty, error)
	SendLog(ctx context.Context, in *LogLineMsg, opts ...grpc.CallOption) (*empty.Empty, error)
}

type bridgeClient struct {
	cc grpc.ClientConnInterface
}

func NewBridgeClient(cc grpc.ClientConnInterface) BridgeClient {
	return &bridgeClient{cc}
}

func (c *bridgeClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	out := new(LoginResp)
	err := c.cc.Invoke(ctx, Bridge_Login_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeClient) Register(ctx context.Context, in *BridgeInfo, opts ...grpc.CallOption) (*RegisterResp, error) {
	out := new(RegisterResp)
	err := c.cc.Invoke(ctx, Bridge_Register_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeClient) GetTargetStream(ctx context.Context, in *JoinStreamReq, opts ...grpc.CallOption) (Bridge_GetTargetStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Bridge_ServiceDesc.Streams[0], Bridge_GetTargetStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &bridgeGetTargetStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Bridge_GetTargetStreamClient interface {
	Recv() (*BridgeTarget, error)
	grpc.ClientStream
}

type bridgeGetTargetStreamClient struct {
	grpc.ClientStream
}

func (x *bridgeGetTargetStreamClient) Recv() (*BridgeTarget, error) {
	m := new(BridgeTarget)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *bridgeClient) CallDnsAcme(ctx context.Context, in *DnsAcmeReq, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, Bridge_CallDnsAcme_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeClient) SendSystemStat(ctx context.Context, in *SystemStat, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, Bridge_SendSystemStat_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeClient) SendRouteInfo(ctx context.Context, in *RouteStat, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, Bridge_SendRouteInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeClient) SendLog(ctx context.Context, in *LogLineMsg, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, Bridge_SendLog_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BridgeServer is the server API for Bridge service.
// All implementations must embed UnimplementedBridgeServer
// for forward compatibility
type BridgeServer interface {
	Login(context.Context, *LoginReq) (*LoginResp, error)
	Register(context.Context, *BridgeInfo) (*RegisterResp, error)
	GetTargetStream(*JoinStreamReq, Bridge_GetTargetStreamServer) error
	CallDnsAcme(context.Context, *DnsAcmeReq) (*empty.Empty, error)
	SendSystemStat(context.Context, *SystemStat) (*empty.Empty, error)
	SendRouteInfo(context.Context, *RouteStat) (*empty.Empty, error)
	SendLog(context.Context, *LogLineMsg) (*empty.Empty, error)
	mustEmbedUnimplementedBridgeServer()
}

// UnimplementedBridgeServer must be embedded to have forward compatible implementations.
type UnimplementedBridgeServer struct {
}

func (UnimplementedBridgeServer) Login(context.Context, *LoginReq) (*LoginResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedBridgeServer) Register(context.Context, *BridgeInfo) (*RegisterResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedBridgeServer) GetTargetStream(*JoinStreamReq, Bridge_GetTargetStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetTargetStream not implemented")
}
func (UnimplementedBridgeServer) CallDnsAcme(context.Context, *DnsAcmeReq) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallDnsAcme not implemented")
}
func (UnimplementedBridgeServer) SendSystemStat(context.Context, *SystemStat) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendSystemStat not implemented")
}
func (UnimplementedBridgeServer) SendRouteInfo(context.Context, *RouteStat) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendRouteInfo not implemented")
}
func (UnimplementedBridgeServer) SendLog(context.Context, *LogLineMsg) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendLog not implemented")
}
func (UnimplementedBridgeServer) mustEmbedUnimplementedBridgeServer() {}

// UnsafeBridgeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BridgeServer will
// result in compilation errors.
type UnsafeBridgeServer interface {
	mustEmbedUnimplementedBridgeServer()
}

func RegisterBridgeServer(s grpc.ServiceRegistrar, srv BridgeServer) {
	s.RegisterService(&Bridge_ServiceDesc, srv)
}

func _Bridge_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bridge_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bridge_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BridgeInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bridge_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServer).Register(ctx, req.(*BridgeInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bridge_GetTargetStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(JoinStreamReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BridgeServer).GetTargetStream(m, &bridgeGetTargetStreamServer{stream})
}

type Bridge_GetTargetStreamServer interface {
	Send(*BridgeTarget) error
	grpc.ServerStream
}

type bridgeGetTargetStreamServer struct {
	grpc.ServerStream
}

func (x *bridgeGetTargetStreamServer) Send(m *BridgeTarget) error {
	return x.ServerStream.SendMsg(m)
}

func _Bridge_CallDnsAcme_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DnsAcmeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServer).CallDnsAcme(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bridge_CallDnsAcme_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServer).CallDnsAcme(ctx, req.(*DnsAcmeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bridge_SendSystemStat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemStat)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServer).SendSystemStat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bridge_SendSystemStat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServer).SendSystemStat(ctx, req.(*SystemStat))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bridge_SendRouteInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteStat)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServer).SendRouteInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bridge_SendRouteInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServer).SendRouteInfo(ctx, req.(*RouteStat))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bridge_SendLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogLineMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServer).SendLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bridge_SendLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServer).SendLog(ctx, req.(*LogLineMsg))
	}
	return interceptor(ctx, in, info, handler)
}

// Bridge_ServiceDesc is the grpc.ServiceDesc for Bridge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Bridge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gwconn.Bridge",
	HandlerType: (*BridgeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Bridge_Login_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _Bridge_Register_Handler,
		},
		{
			MethodName: "CallDnsAcme",
			Handler:    _Bridge_CallDnsAcme_Handler,
		},
		{
			MethodName: "SendSystemStat",
			Handler:    _Bridge_SendSystemStat_Handler,
		},
		{
			MethodName: "SendRouteInfo",
			Handler:    _Bridge_SendRouteInfo_Handler,
		},
		{
			MethodName: "SendLog",
			Handler:    _Bridge_SendLog_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetTargetStream",
			Handler:       _Bridge_GetTargetStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "bridge.proto",
}
